### ISSUE TITLE
unsupported_grant_type: Invalid grant_type: 

### ISSUE THREAD

**Issue by romainmnr** [googleapis/nodejs-storage#1128]
Hi!

Since this morning I'm facing an issue with the storage SDK.
Every functions call return this error: 
```unsupported_grant_type: Invalid grant_type: ```

This error is thrown when trying to get an access token from my service account credentials:
```
 "method": "POST",
 "url": "https://www.googleapis.com/oauth2/v4/token",
 "data": {
    "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
    "assertion": "{JWT token here}"
  },
....
```

The SDK is initialized like this:
```
const storage = new Storage({
    projectId   : Config.google.projectId, // String
    credentials : Config.google.serviceAccount // Object: service account JSON
});
```

Error trace:

```

 "trace": "Error: unsupported_grant_type: Invalid grant_type: 
    at Gaxios._request (/Users/romain/Workspaces/web-light-cloud-core/LCC/node_modules/gaxios/build/src/gaxios.js:85:23)
   at processTicksAndRejections (internal/process/task_queues.js:94:5)
   at async GoogleToken.requestToken (/Users/romain/Workspaces/web-light-cloud-core/LCC/node_modules/gtoken/build/src/index.js:202:23)
   at async JWT.refreshTokenNoCache (/Users/romain/Workspaces/web-light-cloud-core/LCC/node_modules/google-auth-library/build/src/auth/jwtclient.js:156:23)
    at async JWT.getRequestMetadataAsync (/Users/romain/Workspaces/web-light-cloud-core/LCC/node_modules/google-auth-library/build/src/auth/oauth2client.js:266:17)
    at async JWT.getRequestHeaders (/Users/romain/Workspaces/web-light-cloud-core/LCC/node_modules/google-auth-library/build/src/auth/oauth2client.js:245:26)
   at async GoogleAuth.authorizeRequest (/Users/romain/Workspaces/web-light-cloud-core/LCC/node_modules/google-auth-library/build/src/auth/googleauth.js:544:25)",
"message": "unsupported_grant_type: Invalid grant_type: ",

```

#### Environment details

  - OS: macOs Catalina & Linux Buster
  - Node.js version: v12.14.1
  - npm version: 6.13.7
  - `@google-cloud/storage` version: 4.6.0

Thanks!

**Comment by bcoe** [comment]
@romainmnr could you please `rm -rf package-lock.json`, `rm -rf node_modules`, `npm i`.

There was a bad release of a dependency `gaxios` which went out for about 2 hours yesterday, the problem should be addressed now.

**Comment by romainmnr** [comment]
Thanks for your reply.

However I still have the issue...

here my new package-lock.json file:

```
    "@google-cloud/storage": {
      "version": "4.6.0",
      "resolved": "https://npm.lightingsoft.com/@google-cloud%2fstorage/-/storage-4.6.0.tgz",
      "integrity": "sha512-ubhbLAnj+hrp32x5gI+JajKU0kvhApA6PsLOLkuOj4Cz4b6MNsyhSWZ5rq2W7TylqfNNW8M9QxPCKWg3Sb0IbA==",
      "requires": {
        "@google-cloud/common": "^2.1.1",
        "@google-cloud/paginator": "^2.0.0",
        "@google-cloud/promisify": "^1.0.0",
        "arrify": "^2.0.0",
        "compressible": "^2.0.12",
        "concat-stream": "^2.0.0",
        "date-and-time": "^0.12.0",
        "duplexify": "^3.5.0",
        "extend": "^3.0.2",
        "gaxios": "^2.0.1",
        "gcs-resumable-upload": "^2.2.4",
        "hash-stream-validation": "^0.2.2",
        "mime": "^2.2.0",
        "mime-types": "^2.0.8",
        "onetime": "^5.1.0",
        "p-limit": "^2.2.0",
        "pumpify": "^2.0.0",
        "readable-stream": "^3.4.0",
        "snakeize": "^0.1.0",
        "stream-events": "^1.0.1",
        "through2": "^3.0.0",
        "xdg-basedir": "^4.0.0"
      }
    },
```

**Comment by bcoe** [comment]
@romainmnr that is a fairly old version of the `gaxios` dependency, which was what had the issue, which makes me think that perhaps the dependency is still broken, but in one of your sub-dependencies.

Try:

```bash
npm ls | grep gaxios
```

The bad version is `2.3.3`.

A newer version of the `gaxios@2.3.4` was released 30 minutes ago, so if you make sure in your project you run:

```
rm package-lock.json
rm -rf node_modules
npm i
```

---

One thing I notice from your path is you're using a `Workspaces` folder, is there a chance that an additional step is required to update the dependency if you're in a yarn workspace environment?

You can check the version in your workspace by running:

`cat /Users/romain/Workspaces/web-light-cloud-core/LCC/node_modules/gaxios/package.json | grep version`.

**Comment by bcoe** [comment]
@romainmnr just checking in that, hopefully, the above steps helped unblock you?

**Comment by benaubin** [comment]
@bcoe Had this same issue. Your steps worked for me (although we're using Yarn for this project, so I adjusted your instructions accordingly)

**Comment by romainmnr** [comment]
@bcoe yes, gaxios was used by another package!
Everything work now! 
Thank you :)

**Comment by bcoe** [comment]
@romainmnr 👌 awesome, I'm glad you're unblocked.
