### ISSUE TITLE
Latest release is broken

### ISSUE THREAD

**Issue by TriPSs** [googleapis/nodejs-storage#1930]
Issue with latest release throwing:
```
Error: Cannot find module '/xx/node_modules/@google-cloud/storage/build/src/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/xx/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/xx/tools/tasks-runner/gcp-cache.js:40:17)
    at Module._compile (/xx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/xx/node_modules/@google-cloud/storage/package.json',
  requestPath: '@google-cloud/storage'
```

**Comment by ddelgrosso1** [comment]
Hi @TriPSs thanks for bringing this to our attention. This was reported in https://github.com/googleapis/nodejs-storage/issues/1931. Release `5.20.1` should resolve this problem. If it does not, please feel free to reopen.

**Comment by faradaytrs** [comment]
Still broken, now it's ERROR: Could not resolve "../package.json"
